repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-toml
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/hadialqattan/pycln
    rev: v1.3.2
    hooks:
    -   id: pycln
